fan:
  - platform: template
    fans:
      afzuiging_badkamer:
        friendly_name: "Afzuiging badkamer"
        value_template: >
          {{ "off" if states('sensor.fanspeed') == 'Low' else "on" }}
        percentage_template: >
          {% set speedperc = {'Low': 0, 'Medium': 50, 'High': 100} %}
          {{speedperc [states('sensor.fanspeed')]}}
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.fansendhigh
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.fansendlow    
        set_percentage: 
          service: switch.turn_on
          data:
            entity_id: >
              {% set id_mapp = {0:'switch.fansendlow',50:'switch.fansendmedium', 100:'switch.fansendhigh'} %}
              {{id_mapp[percentage]}}
        speed_count: 2
